#!/bin/bash

# Generates list of contributors to file 'AUTHORS'

{
	cat <<-'EOH'
	# File @generated by generate-authors.sh. DO NOT EDIT.
	# This file lists all contributors to the repository.
	# See hack/generate-authors.sh to make modifications.
	EOH
	echo
	git log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf
} > AUTHORS
